name: tflint
description: tflint action
inputs:
  github_token:
    description: 'GitHub Access Token'
    required: true
  working_directory:
    description: 'Working Directory'
    required: true
runs:
  using: composite
  steps:
    - run: tflint --init
      shell: bash
      working-directory: ${{ inputs.working_directory }}
    - run: bash ${{ github.action_path }}/main.sh
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        REVIEWDOG_GITHUB_API_TOKEN: ${{ inputs.github_token }}
        EVENT_NAME: ${{ github.event_name }}
