---
name: actionlint
env:
  AQUA_POLICY_CONFIG: ${{ github.workspace }}/aqua-policy.yaml
on:
  pull_request:
    branches:
    - main
    paths:
    - .github/workflows/*.yaml
    - aqua/actionlint.yaml
    - aqua/reviewdog.yaml
  push:
    branches:
    - main
    paths:
    - .github/workflows/*.yaml
    - aqua/actionlint.yaml
    - aqua/reviewdog.yaml
permissions: {}
jobs:
  test:
    uses: suzuki-shunsuke/actionlint-workflow/.github/workflows/actionlint.yaml@main
    permissions:
      pull-requests: write
